---
- name: download flink tarball
  get_url:
    url: http://apache.claz.org/flink/flink-1.3.2/flink-1.3.2-bin-hadoop27-scala_2.10.tgz
    dest: /home/vagrant

- name: extract flink binary
  shell: "tar xfz /home/vagrant/flink-1.3.2-bin-hadoop27-scala_2.10.tgz"
